- src: https://github.com/mats116/ansible-role-hhvm.git
  name: hhvm

- src: https://github.com/mats116/ansible-role-nginx.git
  name: nginx

- src: https://github.com/mats116/ansible-role-mariadb-server.git
  name: mariadb-server

- src: https://github.com/mats116/ansible-role-wordpress.git
  name: wordpress
